#define JOB_TAG "scospub"

#define TAG_PROJECT	"project"
#define TAG_TOOL	"tool"
#define TAG_TOOLID	"toolid"
#define TAG_CONFIG	"config"
#define TAG_SOURCE	"source"
#define TAG_SVN		"svn"
#define TAG_URL		"url"
#define TAG_CHECKOUTDIR	"checkoutdir"
#define TAG_USERNAME	"username"
#define TAG_PASSWORD	"password"
#define TAG_REVISION	"revision"

#define TAG_TASK	"task"
#define TAG_APPLICATION	"application"
#define TAG_COMMAND_LINE	"command_line"
#define TAG_STDIN_FILENAME	"stdin_filename"
#define TAG_STDOUT_FILENAME	"stdout_filename"
#define TAG_STDERR_FILENAME	"stderr_filename"
